[uwsgi]
virtualenv=.venv
module=run:app
master=true
processes=1
threads=2
http-socket=/opt/bayanat/current/bayanat.sock
chmod-socket=660
vacuum=true
buffer-size=8192
touch-reload=reload.ini
reload-mercy=5
worker-reload-mercy=3
;offload-threads=2
;gevent=100
;wsgi=1
;py-autoreload=1
