[uwsgi]
virtualenv=.venv
module=run:app
master=true
processes=1
threads=2
http=127.0.0.1:5000
vacuum=true
buffer-size=8192
touch-reload=reload.ini
harakiri=360
harakiri-verbose=true
;offload-threads=2
;gevent=100
;wsgi=1
;py-autoreload=1
