# Core Fields Configuration
# These are built-in Bulletin model fields that users can only show/hide/reorder

BULLETIN_CORE_FIELDS = {
    "title": {
        "title": "Title",
        "field_type": "string",
        "ui_component": "text_input",
        "sort_order": 1,
        "visible": True,
        "core": True,
    },
    "sjac_title": {
        "title": "SJAC Title",
        "field_type": "string",
        "ui_component": "text_input",
        "sort_order": 2,
        "visible": True,
        "core": True,
    },
    "description": {
        "title": "Description",
        "field_type": "text",
        "ui_component": "text_area",
        "sort_order": 3,
        "visible": True,
        "core": True,
    },
    "tags": {
        "title": "Tags",
        "field_type": "array",
        "ui_component": "multi_select",
        "sort_order": 4,
        "visible": True,
        "core": True,
    },
    "sources": {
        "title": "Sources",
        "field_type": "relationship",
        "ui_component": "multi_select",
        "sort_order": 5,
        "visible": True,
        "core": True,
    },
    "locations": {
        "title": "Locations",
        "field_type": "relationship",
        "ui_component": "multi_select",
        "sort_order": 6,
        "visible": True,
        "core": True,
    },
    "labels": {
        "title": "Labels",
        "field_type": "relationship",
        "ui_component": "multi_select",
        "sort_order": 7,
        "visible": True,
        "core": True,
    },
    "ver_labels": {
        "title": "Verified Labels",
        "field_type": "relationship",
        "ui_component": "multi_select",
        "sort_order": 8,
        "visible": True,
        "core": True,
    },
    "publish_date": {
        "title": "Publish Date",
        "field_type": "datetime",
        "ui_component": "date_picker",
        "sort_order": 9,
        "visible": True,
        "core": True,
    },
    "documentation_date": {
        "title": "Documentation Date",
        "field_type": "datetime",
        "ui_component": "date_picker",
        "sort_order": 10,
        "visible": True,
        "core": True,
    },
    "status": {
        "title": "Status",
        "field_type": "string",
        "ui_component": "dropdown",
        "sort_order": 11,
        "visible": True,
        "core": True,
        "options": [
            {"label": "Draft", "value": "draft"},
            {"label": "Published", "value": "published"},
            {"label": "Archived", "value": "archived"},
        ],
    },
    "source_link": {
        "title": "Source Link",
        "field_type": "string",
        "ui_component": "text_input",
        "sort_order": 12,
        "visible": True,
        "core": True,
    },
    "comments": {
        "title": "Comments",
        "field_type": "text",
        "ui_component": "text_area",
        "sort_order": 13,
        "visible": True,
        "core": True,
    },
}
