class BulletinColsets(object):

    BULLETIN_FULL = ['class',
                     'id',
                     'title',
                     'title_ar',
                     'sjac_title',
                     'sjac_title_ar',
                     'originid',
                     'assigned_to',
                     'first_peer_reviewer',
                     'locations',
                     'geo_locations',
                     'labels',
                     'ver_labels',
                     'sources',
                     'events',
                     'medias',
                     'bulletin_relations',
                     'actor_relations',
                     'incident_relations',
                     'description',
                     'comments',
                     'source_link',
                     'source_link_type',
                     'ref',
                     'publish_date',
                     'documentation_date',
                     'status',
                     'review',
                     'review_action',
                     'updated_at',
                     'roles']
