"""add original_media_id to media_redaction

Revision ID: 68396035f041
Revises: e4f2a9c8d7b1
Create Date: 2026-06-10 14:16:17.368157

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "68396035f041"
down_revision = "e4f2a9c8d7b1"
branch_labels = None
depends_on = None


def upgrade():
    # Idempotent per step: an unstamped database can already have some of this
    # (see the upgrading guide), and each piece is completed independently
    insp = sa.inspect(op.get_bind())
    if "original_media_id" not in {c["name"] for c in insp.get_columns("media_redaction")}:
        op.add_column(
            "media_redaction", sa.Column("original_media_id", sa.Integer(), nullable=True)
        )
    op.create_index(
        "ix_media_redaction_original_media_id",
        "media_redaction",
        ["original_media_id"],
        unique=False,
        if_not_exists=True,
    )
    fks = {fk["name"] for fk in insp.get_foreign_keys("media_redaction")}
    if "media_redaction_original_media_id_fkey" not in fks:
        op.create_foreign_key(
            "media_redaction_original_media_id_fkey",
            "media_redaction",
            "media",
            ["original_media_id"],
            ["id"],
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("media_redaction", schema=None) as batch_op:
        batch_op.drop_constraint("media_redaction_original_media_id_fkey", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_media_redaction_original_media_id"))
        batch_op.drop_column("original_media_id")

    # ### end Alembic commands ###
