"""add original_media_id to media_redaction

Revision ID: 68396035f041
Revises: e4f2a9c8d7b1
Create Date: 2026-06-10 14:16:17.368157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68396035f041'
down_revision = 'e4f2a9c8d7b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_redaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_media_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_media_redaction_original_media_id'), ['original_media_id'], unique=False)
        batch_op.create_foreign_key(None, 'media', ['original_media_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_redaction', schema=None) as batch_op:
        batch_op.drop_constraint('media_redaction_original_media_id_fkey', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_media_redaction_original_media_id'))
        batch_op.drop_column('original_media_id')

    # ### end Alembic commands ###
