
FROM ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update -y && \
    apt-get install -yq python3-dev python3-venv libjpeg8-dev libzip-dev libxml2-dev libssl-dev libffi-dev libxslt1-dev libmysqlclient-dev libncurses5-dev python-setuptools postgresql postgresql-contrib python3-pip libpq-dev libimage-exiftool-perl postgis ffmpeg

RUN apt clean
RUN apt autoremove

WORKDIR /app

# Sets utf-8 encoding for Python
ENV LANG=C.UTF-8
# Turns off writing .pyc files
ENV PYTHONDONTWRITEBYTECODE=1
# Seems to speed things up
ENV PYTHONUNBUFFERED=1
# The `--copies` option tells `venv` to copy libs and binaries
COPY . /app
RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

RUN . /opt/venv/bin/activate

RUN echo "Building Bayanat container."
RUN pip install -r dev-requirements.txt
RUN ls -la /opt/venv/bin/

COPY ./flask/bin/entrypoint.sh /usr/local/bin/entrypoint.sh

RUN chmod 550 /usr/local/bin/entrypoint.sh

ENV PATH="/opt/venv/bin:$PATH"

ARG ROLE
ENV ROLE=${ROLE}

CMD ["/usr/local/bin/entrypoint.sh"]
